### ISSUE TITLE
Missing some data download files in data path like Hateful memes, UCF101

### ISSUE THREAD

**Issue by quanghuy6997** [usc-sail/fed-multimodal#4]
Thank you for your great work. But could you provide sh files for some datasets like Hateful memes, UCF101 in the data path? 
I tried to download the Hateful memes dataset by myself but the structure is different from your configuration. For example the test.jsonl in the original link of hateful memes dataset does not contain labels like your data_partition.py. And for UCF101 dataset, the download_ucf101.py like the instructions is missing also.

**Comment by tiantiaf0627** [comment]
Thanks for pointing this out. I will check with my colleague on Hateful memes, but would you mind sharing where you downloaded the data? 

For UCF101, we mentioned using the MMAction2 for downloading and preprocessing (extract audios and frames out). To skip this step, I will add the processed features for download so people can start the modeling (I am sick at the moment and cannot work much so that I will finish this hopefully next week). However, if people want to apply other pre-trained models to extract other features, going through MMAction2 is probably unavoidable.

**Comment by quanghuy6997** [comment]
Thanks for your reply and hope you get better soon. For the Hateful memes dataset, I downloaded it on Kaggle. I just found the test_seen.jsonl file on Kaggle and it contains labels, maybe it is the test file that you used in this experiment ?

**Comment by tiantiaf0627** [comment]
I believe I have answered this, but not sure if to the same person. In case, here is the [link](https://www.drivendata.org/competitions/70/hateful-memes-phase-2/page/267/)
